language: smalltalk

jobs:
  include:
    - smalltalk:
      - Squeak32-5.3
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Squeak32-5.3
      env: BUILD_NAME=Squeak32-5.3
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk:
      - Squeak64-5.3
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Squeak64-5.3
      env: BUILD_NAME=Squeak64-5.3
      smalltalk_config: .tests.ston
      os: linux

    - smalltalk:
      - Squeak32-5.2
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Squeak32-5.2
      env: BUILD_NAME=Squeak32-5.2
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk:
      - Squeak64-5.2
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Squeak64-5.2
      env: BUILD_NAME=Squeak64-5.2
      smalltalk_config: .tests.ston
      os: linux

    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0
      env: BUILD_NAME=Pharo32-7.0
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .developmentgroup.ston
      os: linux

    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Pharo64-7.0
      env: BUILD_NAME=Pharo64-7.0
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .developmentgroup.ston
      os: linux

    - smalltalk:
      - Pharo32-8.0
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Pharo32-8.0
      env: BUILD_NAME=Pharo32-8.0
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk:
      - Pharo32-8.0
      smalltalk_config: .corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo32-8.0
      smalltalk_config: .developmentgroup.ston
      os: linux

    - smalltalk:
      - Pharo64-8.0
      smalltalk_config: .default.ston
      os: linux
    - smalltalk:
      - Pharo64-8.0
      env: BUILD_NAME=Pharo64-8.0
      smalltalk_config: .tests.ston
      os: linux
    - smalltalk:
      - Pharo64-8.0
      smalltalk_config: .corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo64-8.0
      smalltalk_config: .developmentgroup.ston
      os: linux
