language: smalltalk
sudo: false

# Squeak 5.0 can't load Traits due to a bug in the class format definition.
# This issue has been fixed in trunk

matrix:
  include:
    - smalltalk:
      - Squeak32-5.1
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Squeak32-5.1
      env: BUILD_NAME=Squeak-5.1
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Squeak32-4.6
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Squeak32-4.6
      env: BUILD_NAME=Squeak-4.6
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Squeak32-4.5
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Squeak32-4.5
      env: BUILD_NAME=Squeak-4.5
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .bleedingedge-default.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0
      env: BUILD_NAME=Pharo-7.0
      smalltalk_config: .bleedingedge-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0 
      smalltalk_config: .bleedingedge-corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .bleedingedge-developmentgroup.ston
      os: linux

    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .bleedingedge-default.ston
      os: linux
    - smalltalk:
      - Pharo64-7.0
      env: BUILD_NAME=Pharo-7.0-64
      smalltalk_config: .bleedingedge-tests.ston
      os: linux
    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .bleedingedge-corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .bleedingedge-developmentgroup.ston
      os: linux

    - smalltalk:
      - Pharo32-6.1
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Pharo32-6.1
      env: BUILD_NAME=Pharo-6.1
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-6.1
      smalltalk_config: .stable-corewithextras.ston
      os: linux

    - smalltalk:
      - Pharo64-6.1
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Pharo64-6.1
      env: BUILD_NAME=Pharo-6.1-64
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo64-6.1
      smalltalk_config: .stable-corewithextras.ston
      os: linux

    - smalltalk:
      - Pharo32-6.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Pharo32-6.0
      env: BUILD_NAME=Pharo-6.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-6.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux
    - smalltalk:
      - Pharo32-5.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Pharo32-5.0
      env: BUILD_NAME=Pharo-5.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-5.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux

    - smalltalk:
      - Pharo32-4.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Pharo32-4.0
      env: BUILD_NAME=Pharo-4.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-4.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux

    - smalltalk:
      - Pharo32-3.0
      smalltalk_config: .stable-default.ston
      os: linux
    - smalltalk:
      - Pharo32-3.0
      env: BUILD_NAME=Pharo-3.0
      smalltalk_config: .stable-tests.ston
      os: linux
    - smalltalk:
      - Pharo32-3.0
      smalltalk_config: .stable-corewithextras.ston
      os: linux
