language: smalltalk
if: commit_message !~ /(\[docs])/

arch: arm64-graviton2 # in AWS over Graviton2 CPU
virt: lxd             # required, routes to a 'full VM' instance 
os: linux             # required for arch different than amd64
dist: focal
group: edge           # required for graviton2 builds

jobs:
  include:
    - smalltalk:
      - Squeak64-trunk
      smalltalk_config: .default.ston
    - smalltalk:
      - Squeak64-trunk
      env: BUILD_NAME=Squeak64-5.4
      smalltalk_config: .tests.ston

    - smalltalk:
      - Squeak32-5.3
      smalltalk_config: .default.ston
    - smalltalk:
      - Squeak32-5.3
      env: BUILD_NAME=Squeak32-5.3
      smalltalk_config: .tests.ston
    - smalltalk:
      - Squeak64-5.3
      smalltalk_config: .default.ston
    - smalltalk:
      - Squeak64-5.3
      env: BUILD_NAME=Squeak64-5.3
      smalltalk_config: .tests.ston

    - smalltalk:
      - Squeak32-5.2
      smalltalk_config: .default.ston
    - smalltalk:
      - Squeak32-5.2
      env: BUILD_NAME=Squeak32-5.2
      smalltalk_config: .tests.ston
    - smalltalk:
      - Squeak64-5.2
      smalltalk_config: .default.ston
    - smalltalk:
      - Squeak64-5.2
      env: BUILD_NAME=Squeak64-5.2
      smalltalk_config: .tests.ston

    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .default.ston
    - smalltalk:
      - Pharo32-7.0
      env: BUILD_NAME=Pharo32-7.0
      smalltalk_config: .tests.ston
    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .corewithextras.ston
    - smalltalk:
      - Pharo32-7.0
      smalltalk_config: .developmentgroup.ston

    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .default.ston
    - smalltalk:
      - Pharo64-7.0
      env: BUILD_NAME=Pharo64-7.0
      smalltalk_config: .tests.ston
    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .corewithextras.ston
    - smalltalk:
      - Pharo64-7.0
      smalltalk_config: .developmentgroup.ston

    - smalltalk:
      - Pharo32-8.0
      smalltalk_config: .default.ston
    - smalltalk:
      - Pharo32-8.0
      env: BUILD_NAME=Pharo32-8.0
      smalltalk_config: .tests.ston
    - smalltalk:
      - Pharo32-8.0
      smalltalk_config: .corewithextras.ston
    - smalltalk:
      - Pharo32-8.0
      smalltalk_config: .developmentgroup.ston

    - smalltalk:
      - Pharo64-8.0
      smalltalk_config: .default.ston
    - smalltalk:
      - Pharo64-8.0
      env: BUILD_NAME=Pharo64-8.0
      smalltalk_config: .tests.ston
    - smalltalk:
      - Pharo64-8.0
      smalltalk_config: .corewithextras.ston
    - smalltalk:
      - Pharo64-8.0
      smalltalk_config: .developmentgroup.ston

    - smalltalk:
      - Pharo64-9.0
      smalltalk_config: .default.ston
    - smalltalk:
      - Pharo64-9.0
      env: BUILD_NAME=Pharo64-9.0
      smalltalk_config: .tests.ston
    - smalltalk:
      - Pharo64-9.0
      smalltalk_config: .corewithextras.ston
    - smalltalk:
      - Pharo64-9.0
      smalltalk_config: .developmentgroup.ston

    - smalltalk:
      - Pharo64-alpha
      smalltalk_config: .default.ston
    - smalltalk:
      - Pharo64-alpha
      env: BUILD_NAME=Pharo64-10.0
      smalltalk_config: .tests.ston
    - smalltalk:
      - Pharo64-alpha
      smalltalk_config: .corewithextras.ston
    - smalltalk:
      - Pharo64-alpha
      smalltalk_config: .developmentgroup.ston
