name: Build Fuel
on:
  workflow_call:
    inputs:
      build_targets:
        required: true
        type: string
      configs:
        required: true
        type: string
jobs:
  build:
    name: "Build ${{ matrix.smalltalk }} ${{ matris.config }}"
    if: ${{!contains(github.event.commits[0].message, '[docs]')}}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: ${{ fromJSON(inputs.build_targets) }}
        configs: ${{ fromJSON(inputs.configs) }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ build_target }}
      - run: smalltalkci -s ${{ build_target }} ${{ config }}
        shell: bash
        timeout-minutes: 5