name: Build Fuel
on: [push]
jobs:
  build_squeak:
    if: ${{!contains(github.event.commits[0].message, '[docs]')}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        smalltalk:
          - Squeak32-5.2
          - Squeak64-5.2
          - Squeak32-5.3
          - Squeak64-5.3
          - Squeak64-trunk
        smalltalk_config:
          - .default.ston
          - .tests.ston
    name: "Build ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}"
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}
        shell: bash
        timeout-minutes: 5
  build_pharo:
    if: ${{!contains(github.event.commits[0].message, '[docs]')}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        smalltalk:
          - Pharo32-7.0
          - Pharo64-7.0
          - Pharo32-8.0
          - Pharo64-8.0
          - Pharo64-9.0
          - Pharo64-alpha
        smalltalk_config:
          - .default.ston
          - .tests.ston
          - .corewithextras.ston
          - .developmentgroup.ston
    name: "Build ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}"
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}
        shell: bash
        timeout-minutes: 5
