name: Build Pharo 13.0
on:
  push:
    branches:
      - Pharo12
  pull_request_target:
    branches:
      - Pharo12
  schedule:
    # Minute [0,59]
    # Hour [0,23]
    # Day of the month [1,31]
    # Month of the year [1,12]
    # Day of the week ([0,6] with 0=Sunday)
    - cron:  '37 4 * * 6'
  workflow_dispatch:
jobs:
  build:
    name: Build Pharo 13.0
    uses: theseion/fuel/.github/workflows/base.yaml@master
    with:
      build_targets: '["Pharo64-alpha"]'
      configs: '[".default.ston", ".tests.ston"]'
      branch: Pharo13