name: Build Pharo 9.0
on:
  push:
  pull_request:
  schedule:
    # Minute [0,59]
    # Hour [0,23]
    # Day of the month [1,31]
    # Month of the year [1,12]
    # Day of the week ([0,6] with 0=Sunday)
    - cron:  '17 4 * * 6'
jobs:
  build:
    name: Build Pharo 9.0
    uses: theseion/fuel/.github/workflows/base.yaml@master
    with:
      build_targets: '["Pharo64-9.0"]'
      configs: '[".default.ston", ".tests.ston", ".debug.ston", ".developmentgroup.ston"]'